import Navbar from '@/components/Navbar/navbar';
import './globals.css';
export const metadata = {
    title: 'Sankalp',
    description: 'Generated by create next app',
};
import { SessionProvider } from 'next-auth/react';
import { ToastContainer } from 'react-toastify';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                {
                    <SessionProvider>
                        <Navbar />
                        {children}
                        <ToastContainer />
                    </SessionProvider>
                }
            </body>
        </html>
    );
}
